### ISSUE TITLE
python2环境转python3环境问题请教

### ISSUE THREAD

**Issue by sixs** [littlepinecone/weibo-login#2]
请问下大佬有python3环境版本的么，我根据大佬的代码转为python3后，验证码验证那步一直出现“休息一下吧”（验证码识别有误），一直转不到python3环境。

**Comment by littlepinecone** [comment]
这个不是python版本的问题, 常用ip去获取验证码就提示这个, 挂个代理就行了

**Comment by sixs** [comment]
同一个代理、同一个账号下，你的代码验证码验证通过，修改后就一直返回错误信息“休息一会吧”，所以应该是生成的轨迹有问题，和代理、账号无关。

**Comment by sixs** [comment]
> 这个不是python版本的问题, 常用ip去获取验证码就提示这个, 挂个代理就行了

同一个代理、同一个账号下，你的代码验证码验证通过，修改后就一直返回错误信息“休息一会吧”，所以应该是生成的轨迹有问题，和代理、账号无关。

**Comment by littlepinecone** [comment]
看了下确实不是代理的原因，你在浏览器里面一直故意画错后面就提示休息一会儿，就是刷太多了，调的时候好像清了下cookies就好了，周末有空再看下

**Comment by sixs** [comment]
> 恩, 需要逼真一点的手势

已解决，验证码获取和验证两个请求需要一定的时间间隔，不然会识别为爬虫，感谢大佬的指导。

**Comment by littlepinecone** [comment]
> > 恩, 需要逼真一点的手势
> 
> 已解决，验证码获取和验证两个请求需要一定的时间间隔，不然会识别为爬虫，感谢大佬的指导。

咦确实是, (仔细想想滑动验证码要时间)
